### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by B0zy**
Update Readme to Read better, Move Sousou, Queen and Dimmer to their own section, Order Contributors in Alphabetical order ( Easier to Read ) There's probably more to be changed in the Readme.

### CODE REVIEW

**Comment by B0zy** [comment]
Should add that we should probably make a CONTRIBUTING.md, the main README should just give an overview of what the project is about, why it was made and where they can learn more about it

**Comment by jusvit** [comment]
> CONTRIBUTING.md

Good idea, do you want to implement it?

**Comment by B0zy** [comment]
> > CONTRIBUTING.md
> 
> Good idea, do you want to implement it?

I'll take a shot at it quickly. Should take like 5 mins

**Comment by B0zy** [comment]
@jusvit Done

**Review by jusvit — APPROVED** [review]

**Pull request merged**
