### PR TITLE
ATM System First Commit

### PR DESCRIPTION
**Pull request by yagizakgun**
Withdraw and deposit functions are currently working properly.
 **Planned Features**
-UI Improvements
-Money Transfer
-Billing
-Banker Job
-Maybe Bank Robbery

image
image

### CODE REVIEW

**Comment by dimmerly** [comment]
I'm going to hold off merging this till I've returned from my holiday, so I can effectively test it/review it.

I'll be back in 1.5 weeks

In any regard, thanks for your contribution.

**Comment by B0zy** [comment]
A small detail I noticed, is that inside your ATMMainMenu razor you've declared ``
@inherits PanelComponent
`` two times. While this wont break it, it should still be corrected.

**Comment by B0zy** [comment]
The Withdraw and Deposite Methods in the Razor Panel could also be condensed into a single function, the entire way its called can also be optimized here is a example for the Withdraw function.
```cs
void WithdrawMoney()

    int amount;

    if (!Int32.TryParse(InputBoxWithdraw.Value, out amount) || amount <= 0)
    {
        Log.Info("Invalid amount");
        return;
    }
    
    if (amount > PlayerState.DepositedBalance)
    {
        var message = "[ATM] You don't have that much money!";
        Log.Info(message);
        Toast.Instance.Show(message);
        return;
    }

    PlayerState.GiveMoney(+amount);
    PlayerState.SetDepositedBalance(PlayerState.DepositedBalance - amount);

    Log.Info($" You have withdrawn ${amount}");
    Toast.Instance.Show($"[ATM] You have withdrawn ${amount}");
}
```

This is ofc all up to Dimmerly to review but theses are just my takes on the PR.

**Comment by yagizakgun** [comment]
B0zy thank you for your contribution I have updated my code. I am waiting for the continuation of your contributions

**Comment by B0zy** [comment]
Looks better to my eyes, I do also like the Visual UI. We should standardize in the future the UI with what colours are used.

**Pull request closed without merging**
