### PR TITLE
Clear Dics before Loading

### PR DESCRIPTION
**Pull request by B0zy**

### CODE REVIEW

**Comment by jusvit** [comment]
Hmm, is this related to an issue? Static constructors are always called prior to field member access, although I don't know how nicely that plays with razor.

**Comment by dimmerly** [comment]
Hmm, is this related to an issue? Static constructors are always called prior to field member access, although I don't know how nicely that plays with razor.

**Comment by B0zy** [comment]
> Hmm, is this related to an issue? Static constructors are always called prior to field member access, although I don't know how nicely that plays with razor.

I've personally ran into some issues prior a week or so ago or a static constructer keeping deleted/removed game resources. I'm unaware if it's still a issue however this is a simple fail safe

**Comment by dimmerly** [comment]
> > Hmm, is this related to an issue? Static constructors are always called prior to field member access, although I don't know how nicely that plays with razor.
> 
> I've personally ran into some issues prior a week or so ago or a static constructer keeping deleted/removed game resources. I'm unaware if it's still a issue however this is a simple fail safe 

Fair enough, I had noticed that sometimes it randomly doesn't work.

**Review by dimmerly — APPROVED** [review]

**Pull request merged**
